nome=input("Digite um funcionário: ")
empresa=input("Digite o nome da empresa: ")
qtde_funcionarios=int(input("Digite a quantidade de funcionários: "))
mediaMensalidade=float(input("Digite a média mensal dos funcionários: "))
print(nome + " trabalha na empresa " + empresa)
print("Possui: ", qtde_funcionarios, " funcionários")
print("A media da mensalidade é: " + str(mediaMensalidade))
print("===============Verifique os tipos de dados abaixos:===============")
print("o tipo de nome é: ", type(nome))
print("o tipo de empresa é: ", type(empresa))
print("o tipo de qtde_funcionarios é: ", type(qtde_funcionarios))
print("o tipo de mediaMensalidade é: ", type(mediaMensalidade))